<a href="https://colab.research.google.com/github/WingedPanzer/mis433/blob/main/Python%20Basics%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Jordan
Welcome, Jordan!


In [2]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)
f = int(f)
#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140
140F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [3]:
# complete your program here
c = input('Please enter the temperature in Celsius: ')

print(c)
c = int(c)

#Convert C to F
f = c * 1.8 + 32
print(f'{c}C is {f} in Fahrenheit. ')


Please enter the temperature in Celsius: 60
60
60C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [4]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
d = int(d)
if m == "C":
  t = d * 1.8 + 32
  n = "Fahrenheit"
else:
  t = (d - 32) * 5/9
  n = "Celsius"
print(f'{d}{m} is {t} in {n}. ')


Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140F is 60.0 in Celsius. 


## Question 2

Have some fun with strings.

In [6]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [7]:
# Find the length of this sentence.
z = len(sentence)
print(z)

48


In [8]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [9]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[10:-9])

eap. Show me the code - Linus


In [10]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [11]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('.',''))

talk is cheap show me the code - linus torvalds


In [12]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in range(len(vowels)):
    sentence.lower().count(vowels[v])
    count += sentence.lower().count(vowels[v])
print(count)


13


In [13]:
# Find the positions (indexes) of all vowels in the sentence.

for i in range(len(sentence)):
    if sentence[i] in vowels:
        print(i)



1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [14]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)
print(cubes)


[0, 1, 8, 27, 64]


In [15]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]
print(cubes)


[0, 1, 8, 27, 64]


In [16]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
list = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(list)


[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [17]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...] Sum of previous two numbers
fibonacci = []
n = input('How many numbers do you want? ')

# add your code here
n = int(n)
if n == 1:
  fibonacci [0]
elif n == 2:
  fibonacci [0,1]
elif n > 2:
  fibonacci = [0,1]
  while len(fibonacci) < n:
    fibonacci.append(fibonacci[-1] + fibonacci[-2]) #takes last element and adds the second to last element and appends fibonacci, allowing for growing list.
print(fibonacci)




How many numbers do you want? 12
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [18]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {"Pfizer" : 0.95, "Moderna" : 0.95 , "AstraZeneca" : 0.72 , "Johnson & Johnson" : 0.66}
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [19]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Johnson & Johnson
0.66


In [20]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict["Sputnik V"] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [21]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict["Sinovac"] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [22]:
# Print vaccines with efficacy lower than 90%.
for v in v_dict:
  if v_dict[v] < 0.9:
    print(v)

AstraZeneca
Johnson & Johnson
Sinovac


In [23]:
# delete the Sinovac vaccine from the dictionary.
v_dict.pop("Sinovac")
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [24]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
sentence = sentence.replace(' ','')
for ch in sentence:
  if ch in ch_dict:
    ch_dict[ch] += 1
  else:
    ch_dict[ch] = 1
# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [25]:
import numpy as np

In [26]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2,4,6,8,10,12,14,16,18,20])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([1,3,5,7,9,11,13,15,17,19])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([range(i,i+10) for i in [0,10,20,30,40,50,60,70,80,90]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape
#M #Used for testing

(10, 10)

In [30]:
# Count the numbers in M with an absolute value greater than 1.
np.sum(np.abs(M) > 1)


np.int64(31)

In [31]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
arr

Row count: 10
column count: 5


array([[15, 14, 13, 13, 11],
       [10, 11, 16, 17, 10],
       [13, 11, 19, 13, 14],
       [16, 10, 16, 10, 12],
       [10, 10, 15, 12, 18],
       [15, 11, 12, 14, 17],
       [18, 16, 10, 13, 10],
       [11, 10, 13, 15, 15],
       [12, 16, 11, 19, 11],
       [16, 15, 15, 16, 16]])

In [32]:
# output the element in the first row and the third column
arr[0,2]

np.int64(13)

In [33]:
# output the element in the second row and the last column
arr[1,-1]

np.int64(10)

In [34]:
# output the second row of the array
arr[1,]

array([10, 11, 16, 17, 10])

In [35]:
# output the second last row of the array
arr[-2,]

array([12, 16, 11, 19, 11])

In [36]:
# output the second column of the array
arr[: ,1]

array([14, 11, 11, 10, 10, 11, 16, 10, 16, 15])

In [37]:
# output the second last column of the array
arr[:,-2]

array([13, 17, 13, 10, 12, 14, 13, 15, 19, 16])

In [38]:
# output the upper-left 3x3 sub-array
arr[0:3,0:3]

array([[15, 14, 13],
       [10, 11, 16],
       [13, 11, 19]])

In [39]:
# output the bottom-left 3x3 sub-array
arr[-3:, :-2]

array([[11, 10, 13],
       [12, 16, 11],
       [16, 15, 15]])

In [40]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[13, 13, 11],
       [16, 17, 10],
       [19, 13, 14]])

In [41]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[13, 15, 15],
       [11, 19, 11],
       [15, 16, 16]])

In [42]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1,51)
# Reshape A to a 5x10 array in the following format:
A= A.reshape(5,10)
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [43]:
# add a row [51,...,60] to A
A = np.append(A, np.arange(51,61).reshape(1,10), axis=0)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [44]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A, [3])
A1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [109]:
A1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [45]:
A2

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [46]:
# Add 10 to each element of A
A1 = A1 + 10
A2 = A2 + 10

In [47]:
A1

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [48]:
A2

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [49]:
# Calculate the square root of each element in A
A1 = np.sqrt(A1)
A2 = np.sqrt(A2)

In [50]:
A1

array([[3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532]])

In [51]:
A2

array([[6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669],
       [7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
        8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027]])

In [52]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [53]:
# Print the mean, standard devietion of all numbers in M
np.std(M)


np.float64(1.003761080388317)

In [54]:
np.mean(M)

np.float64(-0.2447346392225352)

In [55]:
# Print the maximum, 3rd quartile, median, 1st quartile, and minimum in M
np.min(M)


np.float64(-3.3004114248194303)

In [56]:
np.percentile(M, 25)

np.float64(-0.7926570814484069)

In [57]:
np.median(M)

np.float64(-0.3157310938996613)

In [58]:
np.percentile(M, 75)

np.float64(0.42235351970166507)

In [59]:
np.max(M)

np.float64(2.534612936928237)